#
# Makefile for the focaltech touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_FTS_D9_D9P) += focaltech_core.o
obj-$(CONFIG_TOUCHSCREEN_FTS_D9_D9P) += focaltech_i2c.o
